version: '3'
services:
  app:
    image: rails_5.0.6
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
      - DB_NAME="${DB_NAME}"
      - DB_USER="${DB_USER}"
      - DB_PASSWORD="${DB_PASSWORD}"
 #The entrypoint file must have execution permissions(chmod +x)
    entrypoint: ./entrypoint.sh

  db:
    image: mariadb:10.3
    build:
      context: .
      dockerfile: mariadb.Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD="${DB_ROOT_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: mysql -uroot -p"${DB_ROOT_PASSWORD}" -e 'SELECT TRUE'
      test: mysql -u"${DB_USER}" -p"${DB_PASSWORD}" -e 'SELECT TRUE'

volumes:
  db:
