# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee80fea12806dfb96e5d88183b866a508befa5e339b18777d4caf9c852d1045fcff0d9cb34b3a9c359d2b46b3309f66dfeece44d52ee90b8e040db19a972f2eb

test:
  secret_key_base: f1f4fd519b4ac2f5fc19b61f7973fc50deaf37ee14c2d4b05300e2cb72023ced5920ba3ae2eaa82aa19a12b32fd9804f7c01ad9a958c58b6a0522ae82057722e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
